LITERATURE_VAULT = [
  # 一、 【自然与觉醒】—— 找回失落的野性（20本）
  { "id": "nature-01", "category": "自然与觉醒", "title": "瓦尔登湖", "author": "梭罗", "whisper": "今晚，我们去康科德的林间坐坐。" },
  { "id": "nature-02", "category": "自然与觉醒", "title": "阿勒泰的角落", "author": "李娟", "whisper": "戈壁滩上的风，会吹走所有烦恼。" },
  { "id": "nature-03", "category": "自然与觉醒", "title": "沙乡年鉴", "author": "利奥波德", "whisper": "听听土地的心跳。" },
  { "id": "nature-04", "category": "自然与觉醒", "title": "草叶集", "author": "惠特曼", "whisper": "赞美这生机勃勃的灵魂。" },
  { "id": "nature-05", "category": "自然与觉醒", "title": "大地的成长", "author": "汉姆生", "whisper": "像麦苗一样缓慢生长。" },
  { "id": "nature-06", "category": "自然与觉醒", "title": "小森林", "author": "五十岚大介", "whisper": "自然的馈赠，总是安静且充实。" },
  { "id": "nature-07", "category": "自然与觉醒", "title": "活山", "author": "娜恩·谢泼德", "whisper": "走进山峦的内在。" },
  { "id": "nature-08", "category": "自然与觉醒", "title": "低吟的荒野", "author": "西格德·奥尔森", "whisper": "寻找最后的宁静之地。" },
  { "id": "nature-09", "category": "自然与觉醒", "title": "等云到", "author": "志村福美", "whisper": "色彩是自然的语言。" },
  { "id": "nature-10", "category": "自然与觉醒", "title": "荒野的呼唤", "author": "杰克·伦敦", "whisper": "唤醒原始的生命力。" },
  { "id": "nature-11", "category": "自然与觉醒", "title": "寂静的春天", "author": "蕾切尔·卡逊", "whisper": "警惕那寂静背后的代价。" },
  { "id": "nature-12", "category": "自然与觉醒", "title": "林中最后的小孩", "author": "理查德·洛夫", "whisper": "重返童年的森林。" },
  { "id": "nature-13", "category": "自然与觉醒", "title": "众神入梦", "author": "洛伦·艾斯利", "whisper": "在进化中寻找神性。" },
  { "id": "nature-14", "category": "自然与觉醒", "title": "海滨笔记", "author": "贝斯特", "whisper": "潮汐起伏，心绪归宁。" },
  { "id": "nature-15", "category": "自然与觉醒", "title": "醒来的森林", "author": "约翰·巴勒斯", "whisper": "第一声鸟鸣，是世界的呼吸。" },
  { "id": "nature-16", "category": "自然与觉醒", "title": "遥远的房屋", "author": "贝斯顿", "whisper": "在世界的尽头独处。" },
  { "id": "nature-17", "category": "自然与觉醒", "title": "夏日走过山间", "author": "约翰·缪尔", "whisper": "山间的阳光，能穿透灵魂。" },
  { "id": "nature-18", "category": "自然与觉醒", "title": "万物有灵且美", "author": "吉米·哈利", "whisper": "生命的温暖，藏在平凡之中。" },
  { "id": "nature-19", "category": "自然与觉醒", "title": "大河恋", "author": "诺曼·麦克林", "whisper": "所有的记忆都流向那条大河。" },
  { "id": "nature-20", "category": "自然与觉醒", "title": "这里的黎明静悄悄", "author": "鲍里斯·瓦西里耶夫", "whisper": "静谧中藏着伟大的牺牲。" },

  # 二、 【哲思与和解】—— 抚平内心的波澜（20本）
  { "id": "philosophy-01", "category": "哲思与和解", "title": "悉达多", "author": "赫尔曼·黑塞", "whisper": "河流在说话，你听到了吗？" },
  { "id": "philosophy-02", "category": "哲思与和解", "title": "人生的智慧", "author": "叔本华", "whisper": "痛苦的源头，往往是过度的欲望。" },
  { "id": "philosophy-03", "category": "哲思与和解", "title": "沉思录", "author": "马可·奥勒留", "whisper": "守护你内心的那座堡垒。" },
  { "id": "philosophy-04", "category": "哲思与和解", "title": "给青年诗人的信", "author": "里尔克", "whisper": "去爱那些难以解决的问题。" },
  { "id": "philosophy-05", "category": "哲思与和解", "title": "先知", "author": "纪伯伦", "whisper": "智慧在你的沉默中生长。" },
  { "id": "philosophy-06", "category": "哲思与和解", "title": "西绪福斯神话", "author": "加缪", "whisper": "在荒诞中寻找幸福。" },
  { "id": "philosophy-07", "category": "哲思与和解", "title": "活出生命的意义", "author": "弗兰克尔", "whisper": "寻找那个让你坚持下去的意义。" },
  { "id": "philosophy-08", "category": "哲思与和解", "title": "禅者的初心", "author": "铃木俊隆", "whisper": "保持那颗充满好奇的心。" },
  { "id": "philosophy-09", "category": "哲思与和解", "title": "道德经", "author": "老子", "whisper": "上善若水，处众人之所恶。" },
  { "id": "philosophy-10", "category": "哲思与和解", "title": "庄子·秋水", "author": "庄子", "whisper": "北冥有鱼，其名为鲲。" },
  { "id": "philosophy-11", "category": "哲思与和解", "title": "人生信条", "author": "托尔斯泰", "whisper": "真理不在远方。" },
  { "id": "philosophy-12", "category": "哲思与和解", "title": "论自我", "author": "爱默生", "whisper": "相信你自己的内心。" },
  { "id": "philosophy-13", "category": "哲思与和解", "title": "幸福之路", "author": "罗素", "whisper": "幸福是一种习惯。" },
  { "id": "philosophy-14", "category": "哲思与和解", "title": "存在与虚无", "author": "萨特", "whisper": "我们命定是自由的。" },
  { "id": "philosophy-15", "category": "哲思与和解", "title": "悲剧的诞生", "author": "尼采", "whisper": "在痛苦中创造艺术。" },
  { "id": "philosophy-16", "category": "哲思与和解", "title": "花药治愈灵魂", "author": "巴赫", "whisper": "花朵里藏着治愈的力量。" },
  { "id": "philosophy-17", "category": "哲思与和解", "title": "瓦伦丁的日记", "author": "匿名", "whisper": "平凡的日常，也有光芒。" },
  { "id": "philosophy-18", "category": "哲思与和解", "title": "僧侣与哲学家", "author": "马修·里卡德", "whisper": "东西方的对话，心的共鸣。" },
  { "id": "philosophy-19", "category": "哲思与和解", "title": "正念的奇迹", "author": "一行禅师", "whisper": "洗碗时，就只是洗碗。" },
  { "id": "philosophy-20", "category": "哲思与和解", "title": "最后十四堂星期二的课", "author": "米奇·阿尔博姆", "whisper": "学会死亡，才能学会生活。" },

  # 三、 【东方美学】—— 感受微小的确幸（20本）
  { "id": "aesthetic-01", "category": "东方美学", "title": "枕草子", "author": "清少纳言", "whisper": "春天，是破晓时分最美。" },
  { "id": "aesthetic-02", "category": "东方美学", "title": "古都", "author": "川端康成", "whisper": "在京都的樱花下，寻找自我的分身。" },
  { "id": "aesthetic-03", "category": "东方美学", "title": "雪国", "author": "川端康成", "whisper": "穿过县界长长的隧道，便是雪国。" },
  { "id": "aesthetic-04", "category": "东方美学", "title": "细雪", "author": "谷崎润一郎", "whisper": "旧时代的背影，如雪般消散。" },
  { "id": "aesthetic-05", "category": "东方美学", "title": "阴翳礼赞", "author": "谷崎润一郎", "whisper": "光与影交错处的极致美学。" },
  { "id": "aesthetic-06", "category": "东方美学", "title": "浮生六记", "author": "沈复", "whisper": "一蔬一饭，皆是情深。" },
  { "id": "aesthetic-07", "category": "东方美学", "title": "随园食单", "author": "袁枚", "whisper": "食人间烟火，悟天地至理。" },
  { "id": "aesthetic-08", "category": "东方美学", "title": "人间草木", "author": "汪曾祺", "whisper": "草木皆有灵，万物皆可爱。" },
  { "id": "aesthetic-09", "category": "东方美学", "title": "山园小记", "author": "周作人", "whisper": "平淡中见真淳。" },
  { "id": "aesthetic-10", "category": "东方美学", "title": "项脊轩志", "author": "归有光", "whisper": "庭有枇杷树，吾妻死之年所手植也。" },
  { "id": "aesthetic-11", "category": "东方美学", "title": "万历十五年", "author": "黄仁宇", "whisper": "在宏大的历史缝隙中寻路。" },
  { "id": "aesthetic-12", "category": "东方美学", "title": "东京梦华录", "author": "孟元老", "whisper": "回望那座繁华如梦的城。" },
  { "id": "aesthetic-13", "category": "东方美学", "title": "闲情偶寄", "author": "李渔", "whisper": "生活的精致，藏在巧思里。" },
  { "id": "aesthetic-14", "category": "东方美学", "title": "苦竹", "author": "周作人", "whisper": "甘苦自知，宁静致远。" },
  { "id": "aesthetic-15", "category": "东方美学", "title": "雅舍小品", "author": "梁实秋", "whisper": "诙谐与智慧，在茶余饭后。" },
  { "id": "aesthetic-16", "category": "东方美学", "title": "幽梦影", "author": "张潮", "whisper": "赏花、对月、听雨、看山。" },
  { "id": "aesthetic-17", "category": "东方美学", "title": "平如美棠", "author": "饶平如", "whisper": "相濡以沫，便是永恒。" },
  { "id": "aesthetic-18", "category": "东方美学", "title": "草木春秋", "author": "丰子恺", "whisper": "以童心看世界，处处皆风景。" },
  { "id": "aesthetic-19", "category": "东方美学", "title": "缘缘堂随笔", "author": "丰子恺", "whisper": "随遇而安，缘分深厚。" },
  { "id": "aesthetic-20", "category": "东方美学", "title": "边城", "author": "沈从文", "whisper": "那个翠翠，还在等那个年轻人吗？" },

  # 四、 【温暖与童话】—— 回到安全的童年（20本）
  { "id": "fairy-01", "category": "温暖与童话", "title": "小王子", "author": "圣埃克苏佩里", "whisper": "所有的大人都曾经是小孩。" },
  { "id": "fairy-02", "category": "温暖与童话", "title": "夜莺与玫瑰", "author": "王尔德", "whisper": "爱是比生命更伟大的东西。" },
  { "id": "fairy-03", "category": "温暖与童话", "title": "柳林风声", "author": "肯尼斯·格雷厄姆", "whisper": "在河岸边的草丛里做个梦。" },
  { "id": "fairy-04", "category": "温暖与童话", "title": "秘密花园", "author": "伯内特", "whisper": "只要有爱，荒园也会开花。" },
  { "id": "fairy-05", "category": "温暖与童话", "title": "长腿叔叔", "author": "简·韦伯斯特", "whisper": "信件里的希望，照亮了整个世界。" },
  { "id": "fairy-06", "category": "温暖与童话", "title": "绿山墙的安妮", "author": "蒙哥马利", "whisper": "保持你的想象力，即使世界很平庸。" },
  { "id": "fairy-07", "category": "温暖与童话", "title": "海蒂", "author": "斯比丽", "whisper": "阿尔卑斯山的空气，带着雪的清香。" },
  { "id": "fairy-08", "category": "温暖与童话", "title": "木偶奇遇记", "author": "科洛迪", "whisper": "诚实，是变成真正小孩的唯一路径。" },
  { "id": "fairy-09", "category": "温暖与童话", "title": "格林童话", "author": "格林兄弟", "whisper": "在黑森林里，寻找丢失的光。" },
  { "id": "fairy-10", "category": "温暖与童话", "title": "爱丽丝梦游仙境", "author": "刘易斯·卡罗尔", "whisper": "掉进那个疯狂而奇妙的树洞。" },
  { "id": "fairy-11", "category": "温暖与童话", "title": "绿野仙踪", "author": "鲍姆", "whisper": "心、大脑和勇气，你其实早已拥有。" },
  { "id": "fairy-12", "category": "温暖与童话", "title": "彼得·潘", "author": "詹姆斯·巴里", "whisper": "飞向那个永不长大的岛。" },
  { "id": "fairy-13", "category": "温暖与童话", "title": "快乐王子", "author": "王尔德", "whisper": "真正的美，是那颗为他人碎裂的心。" },
  { "id": "fairy-14", "category": "温暖与童话", "title": "天蓝色的彼岸", "author": "希尔", "whisper": "死亡不是终点，遗忘才是。" },
  { "id": "fairy-15", "category": "温暖与童话", "title": "夏洛的网", "author": "怀特", "whisper": "友谊，是编织在晨露里的奇迹。" },
  { "id": "fairy-16", "category": "温暖与童话", "title": "吹小号的天鹅", "author": "怀特", "whisper": "用声音寻找属于你的共鸣。" },
  { "id": "fairy-17", "category": "温暖与童话", "title": "大红狗", "author": "诺尔曼", "whisper": "纯真与善意，可以跨越一切障碍。" },
  { "id": "fairy-18", "category": "温暖与童话", "title": "小银和我", "author": "希梅内斯", "whisper": "在那只小驴的眼里，世界很温柔。" },
  { "id": "fairy-19", "category": "温暖与童话", "title": "獾的礼物", "author": "华莱", "whisper": "即便离开，留下的礼物也将伴你一生。" },
  { "id": "fairy-20", "category": "温暖与童话", "title": "姆明谷的冬天", "author": "托芙·扬松", "whisper": "白雪覆盖下，依然有温暖的冬眠。" },

  # 五、 【时空与回忆】—— 消失在时间的缝隙（20本）
  { "id": "memory-01", "category": "时空与回忆", "title": "追忆似水年华", "author": "普鲁斯特", "whisper": "玛德莱娜小点心的香味，带我回到过去。" },
  { "id": "memory-02", "category": "时空与回忆", "title": "城南旧事", "author": "林海音", "whisper": "长亭外，古道边，芳草碧连天。" },
  { "id": "memory-03", "category": "时空与回忆", "title": "往事与随想", "author": "赫尔岑", "whisper": "在那遥远的冬日，灵魂在思考。" },
  { "id": "memory-04", "category": "时空与回忆", "title": "长河", "author": "沈从文", "whisper": "河流不息，回忆不止。" },
  { "id": "memory-05", "category": "时空与回忆", "title": "平凡的世界", "author": "路遥", "whisper": "在苦难中，寻找奋斗的力量。" },
  { "id": "memory-06", "category": "时空与回忆", "title": "布拉格之恋", "author": "米兰·昆德拉", "whisper": "灵与肉的拉扯，在动荡的时代。" },
  { "id": "memory-07", "category": "时空与回忆", "title": "生命中不能承受之轻", "author": "米兰·昆德拉", "whisper": "我们是如此轻盈，却又如此沉重。" },
  { "id": "memory-08", "category": "时空与回忆", "title": "情人", "author": "玛格丽特·杜拉斯", "whisper": "比起你年轻时的容颜，我更爱你备受摧残的面孔。" },
  { "id": "memory-09", "category": "时空与回忆", "title": "万物简史", "author": "比尔·布莱森", "whisper": "我们都是星尘，由古老的记忆组成。" },
  { "id": "memory-10", "category": "时空与回忆", "title": "暗淡蓝点", "author": "卡尔·萨根", "whisper": "在那粒微尘上，住着所有的爱与战争。" },
  { "id": "memory-11", "category": "时空与回忆", "title": "宇宙", "author": "卡尔·萨根", "whisper": "星空的宏大，映照人类的卑微。" },
  { "id": "memory-12", "category": "时空与回忆", "title": "时间简史", "author": "霍金", "whisper": "宇宙的边界，也是时间的终点。" },
  { "id": "memory-13", "category": "时空与回忆", "title": "孤独的散步者", "author": "卢梭", "whisper": "我曾孤独地走过那些漫长的街道。" },
  { "id": "memory-14", "category": "时空与回忆", "title": "少年维特的烦恼", "author": "歌德", "whisper": "那种忧伤，在每个深夜里发酵。" },
  { "id": "memory-15", "category": "时空与回忆", "title": "大卫·科波菲尔", "author": "狄更斯", "whisper": "回望童年的苦难与成长。" },
  { "id": "memory-16", "category": "时空与回忆", "title": "呼啸山庄", "author": "艾米莉·勃朗特", "whisper": "在那荒凉的旷野上，爱与恨同样猛烈。" },
  { "id": "memory-17", "category": "时空与回忆", "title": "远大前程", "author": "狄更斯", "whisper": "所有的期待，最终都归于平凡。" },
  { "id": "memory-18", "category": "时空与回忆", "title": "尤利西斯", "author": "乔伊斯", "whisper": "意識流的海洋中，我们随风漂泊。" },
  { "id": "memory-19", "category": "时空与回忆", "title": "我是猫", "author": "夏目漱石", "whisper": "以猫的视角，审视这个荒谬的世界。" },
  { "id": "memory-20", "category": "时空与回忆", "title": "草枕", "author": "夏目漱石", "whisper": "山路崎岖，心境超然。" }
]
